title: Sergio Perea

email: contacto@sergioperea.net
github_url: https://github.com/sperea
linkedin_url: https://www.linkedin.com/in/sergperea/
blog_url: https://www.sergioperea.net
twitter_url: https://twitter.com/SergioPereaDev
foto_url: https://www.sergioperea.es

exclude: screenshots, LICENSE, README.md
markdown: kramdown
